repos:
  - repo: local
    hooks:
      - id: chart-testing
        name: run chart-testing
        entry: ct lint --config ct.yaml --debug
        language: system
        types: [text]
        pass_filenames: false
      - id: generate-docs
        name: generate chart readmes
        entry: bash generate-docs.sh
        language: system
        types: [text]
        files: 'charts/.*/values.yaml'
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # - id: check-yaml
      # - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # - repo: https://github.com/psf/black
  #   rev: 22.10.0
  #   hooks:
  #     - id: black
  # - repo: https://github.com/gruntwork-io/pre-commit
  #   rev: v0.1.17
  #   hooks:
  #     - id: terraform-fmt
  #     - id: terraform-validate
  #     - id: tflint
  #     - id: shellcheck
  #     - id: gofmt
  #     - id: golint
  #     - id: helmlint
