{{- if and $.Values.secret.create }}
{{- $secretName := include "alt-verifier.secretName" $ }}
  {{- if gt (int $.Values.nodeCount) (len $.Values.secret.nodeKeys) }}
    {{- fail "nodeKeys less than nodeCount" }}
  {{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
stringData:
  {{- with $.Values.secret.mnemonic }}
  mnemonic: {{ . | quote }}
  {{- end }}
  {{- range $i, $e := $.Values.secret.privateKeys }}
  privateKey{{ $i }}: {{ $e | quote }}
  {{- end }}
  {{- range $i, $e := $.Values.secret.nodeKeys }}
  nodeKey{{ $i }}: {{ $e | quote }}
  {{- end }}
{{- end }}
