apiVersion: v1
kind: Service
metadata:
  name: {{ include "alt-verifier.fullname" $ }}
  labels:
    {{- include "alt-verifier.labels" $ | nindent 4 }}
    index: all
spec:
  type: {{ $.Values.service.type }}
  ports:
    - name: rpc
      port: {{ $.Values.service.rpc }}
      protocol: TCP
      targetPort: rpc
    - name: ws
      port: {{ $.Values.service.ws }}
      protocol: TCP
      targetPort: ws
    - name: prometheus
      port: {{ $.Values.service.prometheus }}
      protocol: TCP
      targetPort: prometheus
  selector:
    {{- include "alt-verifier.selectorLabels" $ | nindent 4 }}
