{{- $fullname := include "alt-verifier.fullname" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "alt-verifier.labels" $ | nindent 4 }}
    index: all
spec:
  type: {{ $.Values.service.type }}
  ports:
    - name: prometheus
      port: {{ $.Values.service.prometheus }}
      protocol: TCP
      targetPort: prometheus
  selector:
    {{- include "alt-verifier.selectorLabels" $ | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-headless
  labels:
    {{- include "alt-verifier.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "alt-verifier.selectorLabels" . | nindent 4 }}
  clusterIP: None
